"""Color tokens for light and dark application themes."""

from __future__ import annotations

from .appearance import THEME_DARK_ID, THEME_LIGHT_ID

THEME_DARK: dict[str, str] = {
    "accent": "#4f6ef7",
    "accent_border": "#6b85f9",
    "accent_border_hover": "#7b93fa",
    "accent_border_light": "#5a7af8",
    "accent_hover": "#3d5ce6",
    "bg_button": "#2a2a32",
    "bg_button_hover": "#34343e",
    "bg_button_pressed": "#3e3e4a",
    "bg_elevated": "#1a1a1f",
    "bg_header": "#1e1e24",
    "bg_header_hover": "#28282f",
    "bg_scroll_track": "#141418",
    "bg_window": "#121212",
    "border": "#2a2a32",
    "border_strong": "#35353f",
    "gradient_end": "#8b5cf6",
    "gradient_start": "#4f6ef7",
    "icon_button": "#e8eaed",
    "icon_fg": "#e8eaed",
    "icon_muted": "#8a94a6",
    "pref_dislike_bg": "#5a2d2d",
    "pref_dislike_fg": "#f0b8b8",
    "pref_dislike_border": "#9a4a4a",
    "pref_like_bg": "#2d5a3d",
    "pref_like_fg": "#b8f0c8",
    "pref_like_border": "#4a9a62",
    "danger_border": "#9a4a4a",
    "danger_btn_border": "#5a2d2d",
    "danger_btn_hover": "#3a2525",
    "danger_text": "#f08080",
    "danger_text_light": "#f0b8b8",
    "dislike_bg": "#1a0f0f",
    "dislike_border": "#5c3a3a",
    "error_border": "#5a3030",
    "header_pressed_bg": "#2d4a7a",
    "like_border": "#2d5a3d",
    "link": "#6eb3ff",
    "live_card_bg": "#1e232a",
    "live_card_border": "#252b34",
    "live_header_bg": "#0f1218",
    "live_like_bg": "#0f1a14",
    "live_root_bg": "#080a0c",
    "live_scroll_bg": "#12161c",
    "live_verdict_low": "#b8f0c8",
    "oauth_notice_bg": "#2a2618",
    "oauth_notice_border": "#5a4d28",
    "oauth_notice_text": "#e8d4a8",
    "risk_card_bg": "#1a1408",
    "scrollbar_arrow": "#6b7a90",
    "scrollbar_arrow_hover": "#d8dee9",
    "scrollbar_handle": "#4d5868",
    "scrollbar_handle_hover": "#556377",
    "scrollbar_pressed": "#5c6a7d",
    "selection_bg": "#3d6ebf",
    "success_bg": "#1e3d32",
    "success_border": "#2d5a40",
    "success_btn": "#4a9a62",
    "success_text": "#6ee7a8",
    "text_disabled": "#8b95a8",
    "text_group": "#b8c0cc",
    "text_heading": "#ffffff",
    "text_muted": "#8a94a6",
    "focus_ring": "#5a9af4",
    "text_on_accent": "#ffffff",
    "text_primary": "#e8eaed",
    "text_secondary": "#9aa3b2",
    "text_tab": "#c8ced8",
    "warning_accent": "#c9a227",
    "warning_bg": "#3d3420",
    "warning_text": "#f5c26b",
}

THEME_LIGHT: dict[str, str] = {
    "gradient_end": "#7c3aed",
    "gradient_start": "#2563eb",
    "icon_button": "#4b5563",
    "icon_fg": "#374151",
    "icon_muted": "#6b7280",
    "pref_dislike_bg": "#fee2e2",
    "pref_dislike_fg": "#991b1b",
    "pref_dislike_border": "#dc2626",
    "pref_like_bg": "#d1fae5",
    "pref_like_fg": "#047857",
    "pref_like_border": "#059669",
    "accent": "#2563eb",
    "accent_border": "#2563eb",
    "accent_border_hover": "#1d4ed8",
    "accent_border_light": "#3b82f6",
    "accent_hover": "#1d4ed8",
    "bg_button": "#e5e7eb",
    "bg_button_hover": "#d1d5db",
    "bg_button_pressed": "#9ca3af",
    "bg_elevated": "#ffffff",
    "bg_header": "#e8eaed",
    "bg_header_hover": "#d1d5db",
    "bg_scroll_track": "#e5e7eb",
    "bg_window": "#f3f4f6",
    "border": "#d1d5db",
    "border_strong": "#9ca3af",
    "danger_border": "#f87171",
    "danger_btn_border": "#dc2626",
    "danger_btn_hover": "#fee2e2",
    "danger_text": "#dc2626",
    "danger_text_light": "#ef4444",
    "dislike_bg": "#fef2f2",
    "dislike_border": "#fca5a5",
    "error_border": "#fca5a5",
    "header_pressed_bg": "#1d4ed8",
    "like_border": "#059669",
    "link": "#1d4ed8",
    "live_card_bg": "#ffffff",
    "live_card_border": "#e5e7eb",
    "live_header_bg": "#f9fafb",
    "live_like_bg": "#ecfdf5",
    "live_root_bg": "#f3f4f6",
    "live_scroll_bg": "#ffffff",
    "live_verdict_low": "#059669",
    "oauth_notice_bg": "#fffbeb",
    "oauth_notice_border": "#fcd34d",
    "oauth_notice_text": "#92400e",
    "risk_card_bg": "#fef9c3",
    "scrollbar_arrow": "#9ca3af",
    "scrollbar_arrow_hover": "#4b5563",
    "scrollbar_handle": "#c4cbd4",
    "scrollbar_handle_hover": "#9ca3af",
    "scrollbar_pressed": "#6b7280",
    "selection_bg": "#3b82f6",
    "success_bg": "#d1fae5",
    "success_border": "#6ee7b8",
    "success_btn": "#059669",
    "success_text": "#047857",
    "text_disabled": "#6b7280",
    "text_group": "#374151",
    "text_heading": "#111827",
    "text_muted": "#374151",
    "focus_ring": "#2563eb",
    "text_on_accent": "#ffffff",
    "text_primary": "#111827",
    "text_secondary": "#374151",
    "text_tab": "#4b5563",
    "warning_accent": "#d97706",
    "warning_bg": "#fef3c7",
    "warning_text": "#b45309",
}

THEMES: dict[str, dict[str, str]] = {
    THEME_DARK_ID: THEME_DARK,
    THEME_LIGHT_ID: THEME_LIGHT,
}


def theme_tokens(theme_id: str) -> dict[str, str]:
    return THEMES.get(theme_id, THEME_DARK)
